In [4]:
import pandas as pd

In [5]:
books = pd.read_csv("data/03_Library Systembook.csv")
customers = pd.read_csv("data/03_Library SystemCustomers.csv")

In [6]:
books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [7]:
customers.head()

   Customer ID   Customer Name
0          1.0        Jane Doe
1          2.0      John Smith
2          3.0      Dan Reeves
3          NaN             NaN
4          5.0  William Holden

In [8]:
books = books.dropna()

In [9]:
books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [10]:
customers = customers.dropna()

In [22]:
customers.head(200)

   Customer ID     Customer Name
0            1          Jane Doe
1            2        John Smith
2            3        Dan Reeves
4            5    William Holden
5            6     Jaztyn Forest
6            7     Jackie Irving
7            8  Matthew Stirling
8            9         Emory Ted

In [21]:
books.head(50)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1,Catcher in the Rye,20/02/2023,25/02/2023,14,1
1,2,Lord of the rings the two towers,24/03/2023,21/03/2023,14,2
2,3,Lord of the rings the return of the kind,29/03/2023,25/03/2023,14,3
3,4,The hobbit,02/04/2023,25/03/2023,14,4
4,5,Dune,02/04/2023,25/03/2023,14,5
5,6,Little Women,02/04/2023,01/05/2023,14,1
6,7,IT,10/04/2063,03/04/2023,14,6
7,8,Misery,15/04/2023,03/04/2023,14,7
8,9,Catch 22,15/04/2023,16/04/2023,14,7
9,10,Animal Farm,20/04/2023,24/04/2023,14,2
10,11,1984,23/04/2023,27/04/2023,14,8
11,12,Little Women,02/04/2023,01/05/2023,14,1
12,13,East of Eden,30/04/2023,05/05/2023,14,2
13,14,America Is in the Heart,01/05/2023,07/05/2023,14,3
14,15,Wuthering Heights,01/05/2023,10/05/2023,14,9
15,16,Dark Tales,15/05/2023,01/06/2023,14,2
16,17,The Bloody Chamber,32/05/2023,04/06/2023,14,3
17,18,Les Miserables,03/06/2023,07/06/2023,14,5
18,19,Dracula,10/06/2023,10/07/2023,14,10
19,20,Frankenstein,01/06/2023,20/06/2023,14,2

In [13]:
books["Id"] = books["Id"].astype(int)

In [14]:
books["Customer ID"] = books["Customer ID"].astype(int)

In [24]:
books.columns = books.columns.str.strip()

In [23]:
#remove "" from Book checkout
books["Book checkout"]=books["Book checkout"].astype(str).str.replace('"', '', regex=False).str.strip()

In [17]:
#convert days allowed to borrow from 2 weeks to days
books["Days allowed to borrow"] = (books["Days allowed to borrow"].astype(str)
.str.extract(r"(\d+)", expand=False)
.astype(int) * 7)

In [34]:
#convert book checkout data to date time 
books["Book checkout"] = pd.to_datetime(
    books["Book checkout"],
    dayfirst=True,
    errors="coerce"
)

In [18]:
#check data types
books[["Book checkout", "Book Returned"]].head()
books.dtypes

Id                         int32
Books                     object
Book checkout             object
Book Returned             object
Days allowed to borrow     int32
Customer ID                int32
dtype: object

In [26]:
books["Book Returned"] = pd.to_datetime(
    books["Book Returned"],
    dayfirst=True,
    errors="coerce"
)

In [25]:
customers["Customer ID"] = customers["Customer ID"].astype(int)