In [9]:
import pandas as pd

dropCount= 0

data = pd.read_csv('03_Library Systembook.csv')

print(f"There are {len(data)} rows in this dataset")
data.head()

There are 114 rows in this dataset

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [10]:
# Converting the date of purchase to date format
try: 
    data['Book checkout'] = data['Book checkout'].str.replace('"', "", regex=True)
    data['Book checkout'] = pd.to_datetime(data['Book checkout'], format='mixed' ) 
    data.head()
except Exception as e:
    print(f"Error Occured: {e}")

Error Occured: Invalid date specified (32/5), at position 16

In [11]:
# Investing the error
data.iloc[16]

Id                                      17.0
Books                     The Bloody Chamber
Book checkout                     32/05/2023
Book Returned                     04/06/2023
Days allowed to borrow               2 weeks
Customer ID                              3.0
Name: 16, dtype: object

In [12]:
# Invalid Rows
data.drop(16, inplace=True)
dropCount += 1

In [13]:
# RETRY Converting the date of purchase to date format
data['Book checkout'] = data['Book checkout'].str.replace('"', "", regex=True)
data['Book checkout'] = pd.to_datetime(data['Book checkout'], format='mixed' ) 
data['Book Returned'] = pd.to_datetime(data['Book Returned'], format='mixed' ) 
data.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3.0
3,4.0,The hobbit,2023-02-04,2023-03-25,2 weeks,4.0
4,5.0,Dune,2023-02-04,2023-03-25,2 weeks,5.0

In [14]:
na_dropped_data = data.dropna()
dropCount +=  len(data) - len(na_dropped_data)
na_dropped_data.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3.0
3,4.0,The hobbit,2023-02-04,2023-03-25,2 weeks,4.0
4,5.0,Dune,2023-02-04,2023-03-25,2 weeks,5.0

In [15]:
data

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3.0
3,4.0,The hobbit,2023-02-04,2023-03-25,2 weeks,4.0
4,5.0,Dune,2023-02-04,2023-03-25,2 weeks,5.0
...,...,...,...,...,...,...
109,NaN,NaN,NaT,NaT,NaN,NaN
110,NaN,NaN,NaT,NaT,NaN,NaN
111,NaN,NaN,NaT,NaT,NaN,NaN
112,NaN,NaN,NaT,NaT,NaN,NaN
113,NaN,NaN,NaT,NaT,NaN,NaN

In [16]:
na_dropped_data

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3.0
3,4.0,The hobbit,2023-02-04,2023-03-25,2 weeks,4.0
4,5.0,Dune,2023-02-04,2023-03-25,2 weeks,5.0
5,6.0,Little Women,2023-02-04,2023-01-05,2 weeks,1.0
6,7.0,IT,2063-10-04,2023-03-04,2 weeks,6.0
7,8.0,Misery,2023-04-15,2023-03-04,2 weeks,7.0
8,9.0,Catch 22,2023-04-15,2023-04-16,2 weeks,7.0
9,10.0,Animal Farm,2023-04-20,2023-04-24,2 weeks,2.0
10,11.0,1984,2023-04-23,2023-04-27,2 weeks,8.0
11,12.0,Little Women,2023-02-04,2023-01-05,2 weeks,1.0
12,13.0,East of Eden,2023-04-30,2023-05-05,2 weeks,2.0
13,14.0,America Is in the Heart,2023-01-05,2023-07-05,2 weeks,3.0
14,15.0,Wuthering Heights,2023-01-05,2023-10-05,2 weeks,9.0
15,16.0,Dark Tales,2023-05-15,2023-01-06,2 weeks,2.0
17,18.0,Les Miserables,2023-03-06,2023-07-06,2 weeks,5.0
18,19.0,Dracula,2023-10-06,2023-10-07,2 weeks,10.0
19,20.0,Frankenstein,2023-01-06,2023-06-20,2 weeks,2.0

In [17]:
# Checking for duplicates
duplicate_data = na_dropped_data.duplicated()
duplicate_data.value_counts()

False    19
Name: count, dtype: int64

In [18]:
# Creating and using a function to enrich the data by adding in the time a book was on loan.
data_enriched = na_dropped_data.copy()

def enrich_dateDuration(colA, colB, df=data_enriched):
    """
    Takes the two input columns and the dataframe to create a new column date_delta which is the difference, in days, between colA and colB.
    
    Note: ColA should be the highest of the expected date columns.
    """
    df['date_delta'] = (df[colA]-df[colB]).dt.days
    return df.head()

enrich_dateDuration(df=data_enriched, colA='Book Returned', colB='Book checkout')

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,date_delta
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0,5
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2.0,-3
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3.0,-4
3,4.0,The hobbit,2023-02-04,2023-03-25,2 weeks,4.0,49
4,5.0,Dune,2023-02-04,2023-03-25,2 weeks,5.0,49

In [19]:
data_enriched = na_dropped_data.copy()
data_enriched['loan_duration'] = (data_enriched['Book Returned'] - data_enriched['Book checkout']).dt.days
data_enriched.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,loan_duration
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0,5
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2.0,-3
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3.0,-4
3,4.0,The hobbit,2023-02-04,2023-03-25,2 weeks,4.0,49
4,5.0,Dune,2023-02-04,2023-03-25,2 weeks,5.0,49

In [20]:
valid_loan_data = data_enriched[data_enriched['loan_duration']>=0]
dropCount += len(data_enriched) - len(valid_loan_data)

valid_loan_data.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,loan_duration
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0,5
3,4.0,The hobbit,2023-02-04,2023-03-25,2 weeks,4.0,49
4,5.0,Dune,2023-02-04,2023-03-25,2 weeks,5.0,49
8,9.0,Catch 22,2023-04-15,2023-04-16,2 weeks,7.0,1
9,10.0,Animal Farm,2023-04-20,2023-04-24,2 weeks,2.0,4

In [21]:
# Checking the length of this final dataset
valid_loan_data.shape[0]

12

In [22]:
# Final Drop Count
print(dropCount)

102

# Cleaning the second CSV

In [24]:
import pandas as pd

customers = pd.read_csv('03_Library SystemCustomers.csv')
print(f"Customers csv has {len(customers)} rows.")
customers.head(n=9)

Customers csv has 9 rows.

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
3          NaN               NaN
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted

In [35]:
customer_drop_count = 0

In [36]:
customers.dropna()
customers

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
3          NaN               NaN
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted

In [37]:
customers_clean = customers.dropna()
customer_drop_count += abs(len(customers) - len(customers_clean))
print(f"Drop Count: {customer_drop_count}")

Drop Count: 1

In [38]:
# Outputing cleaned files
customers_clean.to_csv('customers_clean.csv')
valid_loan_data.to_csv('load_data_cleaned.csv')

# Loading MS SQL Server

In [39]:
!pip install pandas sqlalchemy pyodbc

Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.25)
Requirement already satisfied: pyodbc in c:\programdata\anaconda3\lib\site-packages (5.0.1)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.9.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

Important: 

Create the database manually in MS SQL Server with a new log in user called python_app.

In [2]:
# Checking the ODBC Driver for SQL Server
import pyodbc

# List all ODBC drivers installed on the system
drivers = [driver for driver in pyodbc.drivers()]
print("ODBC Drivers available:")
for driver in drivers:
    print(driver)

ODBC Drivers available:
SQL Server
SQL Server Native Client RDA 11.0
ODBC Driver 17 for SQL Server
Microsoft Access Driver (*.mdb, *.accdb)
Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)
Microsoft Access Text Driver (*.txt, *.csv)

In [3]:
from sqlalchemy import create_engine

# Define the connection string to your MS SQL Server
server = 'localhost'  
database = 'DE5_Module5'
username = 'python_app'
password = 'password'

# Create the connection string with Windows Authentication
connection_string = f'mssql+pyodbc://@{server}/{database}?trusted_connection=yes&driver=ODBC+Driver+17+for+SQL+Server'


# Create the SQLAlchemy engine
engine = create_engine(connection_string)

In [4]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://username:password@server/database?driver=ODBC+Driver+17+for+SQL+Server"
)

In [5]:
# Write the DataFrame to SQL Server
customers_clean.to_sql('customers_bronz', con=engine, if_exists='replace', index=False)
valid_loan_data.to_sql('loans_bonz', con=engine, if_exists='replace', index=False)

NameError: name 'customers_clean' is not defined

In [1]:
# DE Metrics to SSMS as a table
metrics = {
    'Record Loss: Loans': dropCount,
    'Record Loss: Customers': customer_drop_count
}

metrics_df = pd.DataFrame([metrics])

# Writing to the server
metrics_df.to_sql('DE_metrics', con=engine, if_exists='replace', index=False)

NameError: name 'dropCount' is not defined

# Lesson Complete

Data should now be written locally within the database! Test it out manually by operning SQL Server and running

```sql
SELECT * FROM dbo.customers_bronz;

SELECT * FROM dbo.loans_bonz;

SELECT * FROM DE_metrics;
```

In [2]:
from app_refactored import fileLoader

fileLoader('data/newFile')

ModuleNotFoundError: No module named 'app_refactored'